In [1]:
import numpy as np
import pandas as pd
myseries = pd.Series([1, -3, 5, 20])
myseries

0     1
1    -3
2     5
3    20
dtype: int64

In [2]:
myseries2 = pd.Series([1, -3, 5, 20], index = ['a', 'b', 'c', 'd'])
myseries2

a     1
b    -3
c     5
d    20
dtype: int64

In [3]:
myseries2.values



array([ 1, -3,  5, 20], dtype=int64)

In [4]:
myseries2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
myseries2[2]

5

In [6]:
myseries2[0:2]

a    1
b   -3
dtype: int64

In [7]:
myseries2['b']

-3

In [8]:
myseries2[['b','c']]

b   -3
c    5
dtype: int64

In [9]:
myseries2['c'] = 10
myseries2

a     1
b    -3
c    10
d    20
dtype: int64

In [10]:
import numpy as np
myarray = np.array([1,2,3,4])
myseries3 = pd.Series(myarray)
myseries3

0    1
1    2
2    3
3    4
dtype: int32

In [11]:
myseries3[myseries3 >2]

2    3
3    4
dtype: int32

In [13]:
np.log(myseries3)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
dtype: float64

In [14]:
mycolors = pd.Series([1,2,3,4,5,4,3,2], index=['white','black','blue','green','green','yellow', 'black', 'red'])
mycolors

white     1
black     2
blue      3
green     4
green     5
yellow    4
black     3
red       2
dtype: int64

In [15]:
mycolors.unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [16]:
mycolors.value_counts()

4    2
3    2
2    2
5    1
1    1
dtype: int64

In [17]:
mycolors.isin([5,7])

white     False
black     False
blue      False
green     False
green      True
yellow    False
black     False
red       False
dtype: bool

In [18]:
mycolors[mycolors.isin([5,7])]

green    5
dtype: int64

In [19]:
mycolors

white     1
black     2
blue      3
green     4
green     5
yellow    4
black     3
red       2
dtype: int64

In [45]:
type(np.NaN)

float

In [20]:
mydict = {'White': 1000, 'Black': 500, 'Red': 200, 'Green': 1000}
myseries = pd.Series(mydict)
myseries

White    1000
Black     500
Red       200
Green    1000
dtype: int64

In [21]:
data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
myframe = pd.DataFrame(data)
myframe


color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [22]:
mydata = {'Employee Name' : ['Ashley','Tom','Jack','John','Alicia'],
'Specialization' : ['Python','Data Science','Data preparation','Data Analysis','Machine Learning'],
'Experience (years)' : [3,5,8,2,4]}
myframe = pd.DataFrame(mydata)
myframe

Employee Name    Specialization  Experience (years)
0        Ashley            Python                   3
1           Tom      Data Science                   5
2          Jack  Data preparation                   8
3          John     Data Analysis                   2
4        Alicia  Machine Learning                   4

In [23]:
myframe2 = pd.DataFrame(mydata, columns=['Experience (years)', 'Employee Name'])
myframe2

Experience (years) Employee Name
0                   3        Ashley
1                   5           Tom
2                   8          Jack
3                   2          John
4                   4        Alicia

In [24]:
myframe3 = pd.DataFrame(mydata, index=['zero', 'one','two','three','four'])
myframe3

Employee Name    Specialization  Experience (years)
zero         Ashley            Python                   3
one             Tom      Data Science                   5
two            Jack  Data preparation                   8
three          John     Data Analysis                   2
four         Alicia  Machine Learning                   4

In [25]:
np.arange(15).reshape((3,5)) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
myframe4 = pd.DataFrame(np.arange(15).reshape((3,5)), index=['row0','row1','row2'], columns=['col0','col1','col2','col3', 'col4'])
myframe4

col0  col1  col2  col3  col4
row0     0     1     2     3     4
row1     5     6     7     8     9
row2    10    11    12    13    14

In [27]:
myframe4.columns

Index(['col0', 'col1', 'col2', 'col3', 'col4'], dtype='object')

In [28]:
myframe4.index

Index(['row0', 'row1', 'row2'], dtype='object')

In [29]:
myframe4.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
myframe4['col2']

row0     2
row1     7
row2    12
Name: col2, dtype: int32

In [31]:
myframe4.col2


row0     2
row1     7
row2    12
Name: col2, dtype: int32

In [32]:
myframe4

col0  col1  col2  col3  col4
row0     0     1     2     3     4
row1     5     6     7     8     9
row2    10    11    12    13    14

In [33]:
myframe4[1:3]

col0  col1  col2  col3  col4
row1     5     6     7     8     9
row2    10    11    12    13    14

In [34]:
myframe4.index.name = 'Rows'
myframe4.columns.name = 'Columns'
myframe4

Columns  col0  col1  col2  col3  col4
Rows                                 
row0        0     1     2     3     4
row1        5     6     7     8     9
row2       10    11    12    13    14

In [105]:
myframe4['col5'] = np.random.randint(100,  size = 3)
myframe4

Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0        0     1     2     3     4    11
row1        5     6     7     8     9    99
row2       10    11    12    13    14    70

In [106]:
np.random.randint(5,  size = 100)

array([1, 4, 0, 2, 4, 3, 1, 1, 1, 0, 2, 1, 1, 2, 0, 1, 0, 2, 1, 2, 2, 3,
       3, 4, 3, 4, 2, 1, 3, 4, 3, 4, 4, 3, 0, 3, 4, 1, 1, 0, 4, 2, 3, 4,
       0, 4, 4, 4, 1, 0, 2, 1, 3, 0, 2, 1, 1, 0, 1, 0, 1, 1, 4, 0, 4, 1,
       1, 0, 0, 0, 4, 0, 1, 3, 1, 3, 3, 2, 4, 4, 3, 4, 2, 3, 3, 3, 1, 1,
       1, 4, 0, 4, 1, 1, 2, 4, 1, 0, 2, 2])

In [110]:
myframe4['col1'][1] = 1000
myframe4

Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0        0     1     2     3     4    11
row1        5  1000     7     8     9    99
row2       10    11    12    13    14    70

In [112]:
myframe4.isin([1,4,99])

Columns   col0   col1   col2   col3   col4   col5
Rows                                             
row0     False   True  False  False   True  False
row1     False  False  False  False  False   True
row2     False  False  False  False  False  False

In [114]:
myframe4[myframe4.isin([1,4,99])]

Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0      NaN   1.0   NaN   NaN   4.0   NaN
row1      NaN   NaN   NaN   NaN   NaN  99.0
row2      NaN   NaN   NaN   NaN   NaN   NaN

In [139]:
myframe3[myframe3['Experience (years)']>4]

Employee Name    Specialization  Experience (years)
one           Tom      Data Science                   5
two          Jack  Data preparation                   8

In [141]:
myframe3.T

zero           one               two          three  \
Employee Name       Ashley           Tom              Jack           John   
Specialization      Python  Data Science  Data preparation  Data Analysis   
Experience (years)       3             5                 8              2   

                                four  
Employee Name                 Alicia  
Specialization      Machine Learning  
Experience (years)                 4

In [36]:
myseries1 = pd.Series(np.random.rand(5), index=[0,1,2,3,4])
myseries1


0    0.385049
1    0.420417
2    0.906397
3    0.834555
4    0.777901
dtype: float64

In [37]:
myseries2 = pd.Series(np.random.rand(5), index=[5,6,7,8,9])
myseries2


5    0.878411
6    0.038584
7    0.224352
8    0.580093
9    0.418029
dtype: float64

In [38]:
pd.concat([myseries1,myseries2])

0    0.385049
1    0.420417
2    0.906397
3    0.834555
4    0.777901
5    0.878411
6    0.038584
7    0.224352
8    0.580093
9    0.418029
dtype: float64

In [39]:
pd.concat([myseries1, myseries2],axis=1)

0         1
0  0.385049       NaN
1  0.420417       NaN
2  0.906397       NaN
3  0.834555       NaN
4  0.777901       NaN
5       NaN  0.878411
6       NaN  0.038584
7       NaN  0.224352
8       NaN  0.580093
9       NaN  0.418029

In [162]:

pd.concat([myseries1, myseries2],axis=1, keys=['series1','series2'])

series1   series2
0  0.865165       NaN
1  0.305467       NaN
2  0.692341       NaN
3  0.859180       NaN
4  0.004683       NaN
5       NaN  0.670931
6       NaN  0.762998
7       NaN  0.200184
8       NaN  0.266258
9       NaN  0.296408

In [40]:
pd.concat([myframe3, myframe2])

Employee Name    Specialization  Experience (years)
zero         Ashley            Python                   3
one             Tom      Data Science                   5
two            Jack  Data preparation                   8
three          John     Data Analysis                   2
four         Alicia  Machine Learning                   4
0            Ashley               NaN                   3
1               Tom               NaN                   5
2              Jack               NaN                   8
3              John               NaN                   2
4            Alicia               NaN                   4

In [41]:
myframe1 = pd.DataFrame({'Student Name': ['A','B','C'], 'Sex':['M','F','M'], 'Age': [10, 16, 17], 'School': ['Primary','High', 'High']})
myframe1

Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High

In [42]:
myframe2 = pd.DataFrame({'Student Name': ['D','E','A'], 'Class':[9,10,5], 'School': ['High', 'High', 'Primary']})
myframe2

Student Name  Class   School
0            D      9     High
1            E     10     High
2            A      5  Primary

In [43]:
pd.concat([myframe1, myframe2])

Student Name  Sex   Age   School  Class
0            A    M  10.0  Primary    NaN
1            B    F  16.0     High    NaN
2            C    M  17.0     High    NaN
0            D  NaN   NaN     High    9.0
1            E  NaN   NaN     High   10.0
2            A  NaN   NaN  Primary    5.0

In [44]:
pd.merge(myframe1, myframe2)

Student Name Sex  Age   School  Class
0            A   M   10  Primary      5

In [45]:
pd.merge(myframe1, myframe2,on='School')

Student Name_x Sex  Age   School Student Name_y  Class
0              A   M   10  Primary              A      5
1              B   F   16     High              D      9
2              B   F   16     High              E     10
3              C   M   17     High              D      9
4              C   M   17     High              E     10

In [46]:
pd.merge(myframe1, myframe2,on='Student Name')

Student Name Sex  Age School_x  Class School_y
0            A   M   10  Primary      5  Primary

In [47]:
myframe1


Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   16     High
2            C   M   17     High

In [48]:
myframe2

Student Name  Class   School
0            D      9     High
1            E     10     High
2            A      5  Primary

In [49]:
myframe2.columns = ['Student Name2','Class','School2']
myframe2

Student Name2  Class  School2
0             D      9     High
1             E     10     High
2             A      5  Primary

In [50]:
myframe1.join(myframe2)

Student Name Sex  Age   School Student Name2  Class  School2
0            A   M   10  Primary             D      9     High
1            B   F   16     High             E     10     High
2            C   M   17     High             A      5  Primary

In [51]:
myseries1 =  pd.Series([50, 40, 30, 20, 10],index=[1,2,3,4,5])
myseries1

1    50
2    40
3    30
4    20
5    10
dtype: int64

In [52]:
myseries2 = pd.Series([100, 200, 300, 400],index=[3,4,5,6])
myseries2

3    100
4    200
5    300
6    400
dtype: int64

In [53]:
myseries1.combine_first(myseries2)


1     50.0
2     40.0
3     30.0
4     20.0
5     10.0
6    400.0
dtype: float64

In [54]:
myseries2.combine_first(myseries1)

1     50.0
2     40.0
3    100.0
4    200.0
5    300.0
6    400.0
dtype: float64

In [55]:
myframe5 = pd.DataFrame({'Student Name': ['A','B','C'], 'Sex':['M','F','M'], 'Age': [10, 16, 17], 'School': ['Primary','High', 'High']})
del myframe5['School']
myframe5

Student Name Sex  Age
0            A   M   10
1            B   F   16
2            C   M   17

In [56]:
myframe5.drop(1)

Student Name Sex  Age
0            A   M   10
2            C   M   17

In [57]:
item_frame = pd.DataFrame({'Items':['Ball','Bat','Hockey','Football','Ball'],'Color':['White','Gray','White', 'Red','White'],'Price':[100,500,700,200,100]})
item_frame


Items  Color  Price
0      Ball  White    100
1       Bat   Gray    500
2    Hockey  White    700
3  Football    Red    200
4      Ball  White    100

In [58]:
item_frame.drop_duplicates()

Items  Color  Price
0      Ball  White    100
1       Bat   Gray    500
2    Hockey  White    700
3  Football    Red    200

In [59]:
import pandas as pd
import numpy as np
myseries4 = pd.Series([10, 20, 30, 40, 50, np.NaN], index=[0,1,2,3,4,5])

print (myseries4.isnull())
myseries4[myseries4.isnull()]

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool


5   NaN
dtype: float64

In [60]:
item_frame.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [63]:
item_frame[item_frame.duplicated()]

Items  Color  Price
4  Ball  White    100

In [64]:
student_frame = pd.DataFrame({'Student Name': ['A','B','C', 'D','E','F','G'], 'Sex':['M','F','M','F','F','M','M'], 'Age': [10, 14, 60, 15, 16, 15, 11], 'School': ['Primary','High', 'High', 'High', 'High','High','Primary']})
student_frame

Student Name Sex  Age   School
0            A   M   10  Primary
1            B   F   14     High
2            C   M   60     High
3            D   F   15     High
4            E   F   16     High
5            F   M   15     High
6            G   M   11  Primary

In [65]:
student_frame.describe()

Age
count   7.000000
mean   20.142857
std    17.714670
min    10.000000
25%    12.500000
50%    15.000000
75%    15.500000
max    60.000000

In [66]:
student_frame.std()

Age    17.71467
dtype: float64

In [70]:
Q1 = student_frame.quantile(0.25)       # 25% or quartile 1 (Q1)
Q3 = student_frame.quantile(0.75)       # 75% or quartile 3 (Q3)
IQR = Q3 - Q1                           # Inter Quartile Range (IQR)
IQR_mult = IQR*1.5
lower= Q1 - IQR_mult                 
upper= Q3 + IQR_mult
print("The lower limit is = ", lower)
print("The upper limit is = ", upper)


The lower limit is =  Age    8.0
dtype: float64
The upper limit is =  Age    20.0
dtype: float64


In [71]:
student_frame2 = student_frame['Age']
student_frame2

0    10
1    14
2    60
3    15
4    16
5    15
6    11
Name: Age, dtype: int64

In [72]:
student_frame['Age'] = pd.Series([x for x in student_frame['Age'] if (x > int(lower))])
student_frame['Age'] = pd.Series([x for x in student_frame['Age'] if (x < int(upper))])
student_frame['Age']

0    10.0
1    14.0
2    15.0
3    16.0
4    15.0
5    11.0
6     NaN
Name: Age, dtype: float64

In [96]:
student_frame['Age']

0    10
1    14
2    60
3    15
4    16
5    15
6    11
Name: Age, dtype: int64

In [75]:
student_frame = student_frame[student_frame['Age'] > int(lower)] 
student_frame = student_frame[student_frame['Age'] < int(upper)]
student_frame

Student Name Sex   Age   School
0            A   M  10.0  Primary
1            B   F  14.0     High
2            C   M  15.0     High
3            D   F  16.0     High
4            E   F  15.0     High
5            F   M  11.0     High

In [76]:
# missing values 
myseries4 = pd.Series([10, 20, 30, None, 40, 50, np.NaN], index=[0,1,2,3,4,5,6])
print (myseries4.isnull())
myseries4

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool


0    10.0
1    20.0
2    30.0
3     NaN
4    40.0
5    50.0
6     NaN
dtype: float64

In [77]:
myseries4[myseries4.isnull()]

3   NaN
6   NaN
dtype: float64

In [78]:
myseries4_dropped = myseries4.dropna()
myseries4_dropped

0    10.0
1    20.0
2    30.0
4    40.0
5    50.0
dtype: float64

In [79]:
myseries4_filled = myseries4.fillna(myseries4.mean())
myseries4_filled

0    10.0
1    20.0
2    30.0
3    30.0
4    40.0
5    50.0
6    30.0
dtype: float64

In [80]:
data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
myframe = pd.DataFrame(data)
myframe

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [81]:
mymap = {'blue':'dark blue', 'green': 'light green'}
myframe.replace(mymap)

color  object  price
0    dark blue    ball    1.2
1  light green     pen    1.0
2       yellow  pencil    0.6
3          red   paper    0.9
4        white     mug    1.7

In [82]:
myseries = pd.Series([1,2,np.nan,4,5,np.nan])
myseries.replace(np.nan,0)


0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
5    0.0
dtype: float64

In [83]:
mymap2 = {'ball':'round', 'pencil':'long', 'pen': 'long', 'mug': 'cylindrical', 'paper':'rectangular'}
myframe['shape']=myframe['object'].map(mymap2)
myframe

color  object  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical

In [85]:
reindex = { 0: 'first', 1: 'second', 2: 'third', 3: 'fourth', 4: 'fifth'}


In [86]:
myframe.rename(reindex)
myframe

color  object  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical

In [190]:
myframe_new = myframe
myframe_new.rename(index={'first':1}, columns={'object':'item'})

color    item  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical

In [188]:
myframe

color  object  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical

In [90]:
#readings = np.random.randint(1,100,20)
readings= [34, 39, 82, 75, 16, 17, 15, 74, 37, 68, 22, 92, 99, 54, 39, 96, 17, 36, 91, 86]
readings

[34,
 39,
 82,
 75,
 16,
 17,
 15,
 74,
 37,
 68,
 22,
 92,
 99,
 54,
 39,
 96,
 17,
 36,
 91,
 86]

In [91]:
bins = [0,25,50,75,100]

In [92]:
mycategory = pd.cut(readings, bins)
mycategory

[(25, 50], (25, 50], (75, 100], (50, 75], (0, 25], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 20
Categories (4, interval[int64]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [93]:
mycategory.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]],
              closed='right',
              dtype='interval[int64]')

In [94]:
pd.value_counts(mycategory)

(75, 100]    6
(25, 50]     5
(0, 25]      5
(50, 75]     4
dtype: int64

In [95]:
bin_names = ['Poor','Below Average','Average','Good']
pd.cut(readings, bins, labels=bin_names)

[Below Average, Below Average, Good, Average, Poor, ..., Good, Poor, Below Average, Good, Good]
Length: 20
Categories (4, object): [Poor < Below Average < Average < Good]

In [96]:
pd.qcut(readings, 4)

[(31.0, 46.5], (31.0, 46.5], (46.5, 83.0], (46.5, 83.0], (14.999, 31.0], ..., (83.0, 99.0], (14.999, 31.0], (31.0, 46.5], (83.0, 99.0], (83.0, 99.0]]
Length: 20
Categories (4, interval[float64]): [(14.999, 31.0] < (31.0, 46.5] < (46.5, 83.0] < (83.0, 99.0]]

In [97]:
pd.value_counts(pd.qcut(readings,4))

(83.0, 99.0]      5
(46.5, 83.0]      5
(31.0, 46.5]      5
(14.999, 31.0]    5
dtype: int64

In [98]:
myframe.shape

(5, 4)

In [254]:

myframe.info

<bound method DataFrame.info of     color  object  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical>

In [99]:
myframe

color  object  price        shape
0    blue    ball    1.2        round
1   green     pen    1.0         long
2  yellow  pencil    0.6         long
3     red   paper    0.9  rectangular
4   white     mug    1.7  cylindrical

In [100]:
data = {'color' : ['blue','white','red','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
myframe = pd.DataFrame(data)
myframe

color  object  price
0   blue    ball    1.2
1  white     pen    1.0
2    red  pencil    0.6
3    red   paper    0.9
4  white     mug    1.7

In [101]:
mygroup = myframe['price'].groupby(myframe['color'])
mygroup

In [102]:
myframe2 = myframe
myframe2.loc[5]=['red','pencil',0.8]
myframe2


color  object  price
0   blue    ball    1.2
1  white     pen    1.0
2    red  pencil    0.6
3    red   paper    0.9
4  white     mug    1.7
5    red  pencil    0.8

In [103]:
mygroup2 = myframe2['price'].groupby([myframe2['color'],myframe2['object']])

In [104]:
mygroup2.groups

{('blue', 'ball'): Int64Index([0], dtype='int64'),
 ('red', 'paper'): Int64Index([3], dtype='int64'),
 ('red', 'pencil'): Int64Index([2, 5], dtype='int64'),
 ('white', 'mug'): Int64Index([4], dtype='int64'),
 ('white', 'pen'): Int64Index([1], dtype='int64')}

In [105]:
mygroup2.mean()

color  object
blue   ball      1.2
red    paper     0.9
       pencil    0.7
white  mug       1.7
       pen       1.0
Name: price, dtype: float64

In [106]:
mygroup2.sum()

color  object
blue   ball      1.2
red    paper     0.9
       pencil    1.4
white  mug       1.7
       pen       1.0
Name: price, dtype: float64

In [107]:
myframe4.columns

Index(['col0', 'col1', 'col2', 'col3', 'col4'], dtype='object', name='Columns')

In [108]:
myframe4.index

Index(['row0', 'row1', 'row2'], dtype='object', name='Rows')

In [109]:
myframe4.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [110]:
myframe4['col2']

Rows
row0     2
row1     7
row2    12
Name: col2, dtype: int32

In [111]:
myframe4.col2

Rows
row0     2
row1     7
row2    12
Name: col2, dtype: int32

In [112]:
myframe4[1:3]

Columns  col0  col1  col2  col3  col4
Rows                                 
row1        5     6     7     8     9
row2       10    11    12    13    14

In [113]:
myframe4.loc['row1']

Columns
col0    5
col1    6
col2    7
col3    8
col4    9
Name: row1, dtype: int32

In [114]:
myframe4.index.name = 'Rows'
myframe4.columns.name = 'Columns'
myframe4


Columns  col0  col1  col2  col3  col4
Rows                                 
row0        0     1     2     3     4
row1        5     6     7     8     9
row2       10    11    12    13    14

In [115]:
myframe4['col5'] = np.random.randint(100,  size = 3)
myframe4


Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0        0     1     2     3     4     9
row1        5     6     7     8     9    21
row2       10    11    12    13    14     8

In [116]:
myframe4['col1'][1] = 1000
myframe4


Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0        0     1     2     3     4     9
row1        5  1000     7     8     9    21
row2       10    11    12    13    14     8

In [117]:
myframe4.isin([1,4,99])

Columns   col0   col1   col2   col3   col4   col5
Rows                                             
row0     False   True  False  False   True  False
row1     False  False  False  False  False  False
row2     False  False  False  False  False  False

In [118]:
myframe4[myframe4.isin([1,4,99])]

Columns  col0  col1  col2  col3  col4  col5
Rows                                       
row0      NaN   1.0   NaN   NaN   4.0   NaN
row1      NaN   NaN   NaN   NaN   NaN   NaN
row2      NaN   NaN   NaN   NaN   NaN   NaN

In [119]:
del myframe4['col5']
myframe4


Columns  col0  col1  col2  col3  col4
Rows                                 
row0        0     1     2     3     4
row1        5  1000     7     8     9
row2       10    11    12    13    14

In [120]:
myframe3

Employee Name    Specialization  Experience (years)
zero         Ashley            Python                   3
one             Tom      Data Science                   5
two            Jack  Data preparation                   8
three          John     Data Analysis                   2
four         Alicia  Machine Learning                   4

In [121]:
myframe3[myframe3['Experience (years)']>4]

Employee Name    Specialization  Experience (years)
one           Tom      Data Science                   5
two          Jack  Data preparation                   8

In [122]:
myframe3.T

zero           one               two          three  \
Employee Name       Ashley           Tom              Jack           John   
Specialization      Python  Data Science  Data preparation  Data Analysis   
Experience (years)       3             5                 8              2   

                                four  
Employee Name                 Alicia  
Specialization      Machine Learning  
Experience (years)                 4